"""
  Apenas constantes usadas no jogo.
"""

SCREEN_WIDTH = 600
SCREEN_HEIGHT = 400
PLAYER_WIDTH = 100
PLAYER_HEIGHT = 120
PLAYER_SIZE = (PLAYER_WIDTH, PLAYER_HEIGHT)
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)
FLOOR  = SCREEN_HEIGHT - PLAYER_HEIGHT - 10
VEHICLE_SPEED = 10
BG_1_SPEED = 1
BG_2_SPEED = 2
BG_3_SPEED = 3
FPS = 60